### ISSUE TITLE
Missing names for Linux + Mac for the Runtime API

### ISSUE THREAD

**Issue by p0nce** [DerelictOrg/DerelictCUDA#2]
https://github.com/DerelictOrg/DerelictCUDA/blob/master/source/derelict/cuda/runtimeapi.d#L42

**Comment by p0nce** [comment]
http://forum.dlang.org/post/mc7cg8$1aik$1@digitalmars.com

**Comment by kubasz** [comment]
I guess you still don't have the names, I use Arch Linux, and apparently none of the NVIDIA driver packages install the runtime library. However, the CUDA SDK package installs it in /opt/cuda/lib/libcudart.so and (the 64-bit version)  /opt/cuda/lib64/libcudart.so . CUDA 7.0-specific name is libcudart.so.7.0. Ubuntu package libcudart6.5 installs the runtime API in /usr/lib/x86_64-linux-gnu/libcudart.so.6.5 according to their webpage.
Sources:
https://www.archlinux.org/packages/community/x86_64/cuda/
http://packages.ubuntu.com/vivid/amd64/libcudart6.5/filelist

**Comment by p0nce** [comment]
Thanks. Do you happen to have the names for the Driver API too?

**Comment by p0nce** [comment]
https://github.com/DerelictOrg/DerelictCUDA/commit/c8ce70f2df830f8b3aa7910040d784b8a9355587
